import type { Speaker } from '~/types/speakers'

export const speakers: Speaker[] = [
  {
    id: 'speaker_1',
    code: 'mosky',
    displayName: 'Mosky',
    jobTitle: 'ex-test-test-test-test-test-test JOB Title',
    avatar: '/speakers/avatar_mosky.png',
    socialLinks: [
      {
        type: 'facebook',
        url: 'https://www.facebook.com/mosky.tw',
      },
      {
        type: 'x',
        url: 'https://x.com/moskytw',
      },
      {
        type: 'website',
        url: 'https://www.facebook.com/mosky.tw',
      },
      {
        type: 'instagram',
        url: 'https://www.instagram.com/mosky.tw',
      },
    ],
  },
  {
    id: 'speaker_2',
    code: 'lydia',
    displayName: '郭藺瑩 Lydia',
    avatar: '/speakers/avatar_lydia.png',
  },
  {
    id: 'speaker_3',
    code: 'ihower',
    jobTitle: 'ex-test-test-test-test-test-test JOB Title',
    displayName: '張文鈿 iHower',
    avatar: '/speakers/avatar_ihower.png',
    socialLinks: [
      {
        type: 'facebook',
        url: 'https://www.facebook.com/mosky.tw',
      },
      {
        type: 'x',
        url: 'https://x.com/moskytw',
      },
    ],
  },
  {
    id: 'speaker_4',
    code: 'pjwang',
    displayName: '王鵬傑 PJ Wang',
    avatar: '/speakers/avatar_pjwang.png',
  },
  {
    id: 'speaker_5',
    code: 'kuro',
    displayName: 'Kuro Hsu',
    avatar: '/speakers/avatar_kuro.png',
  },
  {
    id: 'speaker_6',
    code: 'djlee',
    displayName: '李德俊 (紅豆)',
    avatar: '/speakers/avatar_djlee.png',
  },
  {
    id: 'speaker_7',
    code: 'samuel',
    displayName: '高玉璁 Samuel',
    avatar: '/speakers/avatar_samuel.png',
  },
  {
    id: 'speaker_8',
    code: 'yuanlin',
    displayName: '林沅霖 Yuanlin Lin',
    avatar: '/speakers/avatar_yuanlin.png',
  },
  {
    id: 'speaker_9',
    code: 'summer',
    displayName: 'Summer',
    avatar: '/speakers/avatar_summer.png',
  },
  {
    id: 'speaker_10',
    code: 'maylogger',
    displayName: '設計師勞哥',
    avatar: '/speakers/avatar_maylogger.png',
  },
  {
    id: 'speaker_11',
    code: 'weithenn',
    displayName: '王偉任 Weithenn',
    avatar: '/speakers/avatar_weithenn.png',
  },
  {
    id: 'speaker_12',
    code: 'zet',
    displayName: 'Zet',
    avatar: '/speakers/avatar_zet.png',
  },
  {
    id: 'speaker_13',
    code: 'milkmidi',
    displayName: '奶綠茶',
    avatar: '/speakers/avatar_milkmidi.png',
  },
  {
    id: 'speaker_14',
    code: 'amos',
    displayName: '李建杭 Amos',
    avatar: '/speakers/avatar_amos.png',
  },
  {
    id: 'speaker_15',
    code: 'taiming',
    displayName: 'Taiming',
    avatar: '/speakers/avatar_taiming.png',
  },
  {
    id: 'speaker_16',
    code: 'nic',
    displayName: '在地上滾的工程師 Nic',
    avatar: '/speakers/avatar_nic.png',
  },
  {
    id: 'speaker_17',
    code: 'rei',
    displayName: '黃睿霖 Rei',
    avatar: '/speakers/avatar_huangruilin.png',
  },
  {
    id: 'speaker_18',
    code: 'antfu',
    displayName: 'Anthony Fu',
    avatar: '/speakers/avatar_antfu.png',
  },
  {
    id: 'speaker_19',
    code: 'gugu',
    displayName: 'GUGU',
    avatar: '/speakers/avatar_gugu.png',
  },
  {
    id: 'speaker_20',
    code: 'leo',
    displayName: 'Leo 李歐',
    avatar: '/speakers/avatar_leo.png',
  },
  {
    id: 'speaker_21',
    code: 'sylviauk',
    displayName: '李郁欣',
    avatar: '/speakers/avatar_sylviauk.png',
  },
  {
    id: 'speaker_22',
    code: 'stevenyeo',
    displayName: '楊時鈞 Steven Yeo',
    avatar: '/speakers/avatar_stevenyeo.png',
  },
  {
    id: 'speaker_23',
    code: 'stevenyeh',
    displayName: '史蒂夫·葉',
    avatar: '/speakers/avatar_stevenyeh.png',
  },
  {
    id: 'speaker_24',
    code: 'doppler',
    displayName: '郭丞哲 Doppler kuo',
    avatar: '/speakers/avatar_doppler.png',
  },
  {
    id: 'speaker_25',
    code: 'weikan',
    displayName: '甘韋',
    avatar: '/speakers/avatar_weikan.png',
  },
  {
    id: 'speaker_26',
    code: 'ivanwei',
    displayName: '魏銘信 Ivan Wei',
    avatar: '/speakers/avatar_ivanwei.png',
  },
  {
    id: 'speaker_27',
    code: 'iris',
    displayName: '劉宥筠 Iris',
    avatar: '/speakers/avatar_iris.png',
  },
  {
    id: 'speaker_28',
    code: 'ruddy',
    displayName: '李智樺 Ruddy',
    avatar: '/speakers/avatar_ruddy.png',
  },
  {
    id: 'speaker_29',
    code: 'lindsay',
    displayName: '謝舒婷 (小雨)',
    avatar: '/speakers/avatar_lindsay.png',
  },
  {
    id: 'speaker_30',
    code: 'wylin',
    displayName: '林威宇',
    avatar: '/speakers/avatar_wylin.png',
  },
  {
    id: 'speaker_31',
    code: 'leethi',
    displayName: '海馬',
    avatar: '/speakers/avatar_leethi.png',
  },
  {
    id: 'speaker_32',
    code: 'singz',
    displayName: 'Singz Hsieh',
    avatar: '/speakers/avatar_singz.png',
  },
  {
    id: 'speaker_33',
    code: 'dscareer',
    displayName: '維元',
    avatar: '/speakers/avatar_dscareer.png',
  },
  {
    id: 'speaker_34',
    code: 'lightda',
    displayName: '賴怡玲 (小賴)',
    avatar: '/speakers/avatar_lightda.png',
  },
  {
    id: 'speaker_35',
    code: 'kewang',
    displayName: 'Kewang',
    avatar: '/speakers/avatar_kewang.png',
  },
  {
    id: 'speaker_36',
    code: 'chacha',
    displayName: '劉又瑄 (叉叉)',
    avatar: '/speakers/avatar_chacha.png',
  },
  {
    id: 'speaker_37',
    code: 'hungweichiu',
    displayName: '邱宏瑋',
    avatar: '/speakers/avatar_hungweichiu.png',
  },
  {
    id: 'speaker_38',
    code: 'henrylin',
    displayName: '林義閎',
    avatar: '/speakers/avatar_henrylin.png',
  },
  {
    id: 'speaker_39',
    code: 'gipi',
    displayName: '游舒帆',
    avatar: '/speakers/avatar_gipi.png',
  },
  {
    id: 'speaker_40',
    code: 'kyocheng',
    displayName: 'Kyo Cheng',
    avatar: '/speakers/avatar_kyocheng.png',
    socialLinks: [
      {
        type: 'facebook',
        url: 'https://www.facebook.com/mosky.tw',
      },
      {
        type: 'x',
        url: 'https://x.com/moskytw',
      },
      {
        type: 'instagram',
        url: 'https://www.instagram.com/mosky.tw',
      },
    ],
  },
  {
    id: 'speaker_41',
    code: 'seal',
    displayName: 'Seal Tseng',
    avatar: '/speakers/avatar_seal.png',
  },
  {
    id: 'speaker_42',
    code: 'fin',
    displayName: 'Fin',
    avatar: '/speakers/avatar_fin.png',
  },
]
